//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouseGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataWarehousesProjectEntities : DbContext
    {
        public DataWarehousesProjectEntities()
            : base("name=DataWarehousesProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Klub> Klub { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TransferZawodnika> TransferZawodnika { get; set; }
        public virtual DbSet<WartoscZawodnika> WartoscZawodnika { get; set; }
        public virtual DbSet<Zawodnik> Zawodnik { get; set; }
    }
}
