//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfermarktDataGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferZawodnika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferZawodnika()
        {
            this.SprzedażKupnoZawodnika = new HashSet<SprzedażKupnoZawodnika>();
        }
    
        public int Id { get; set; }
        public System.DateTime DataTransferu { get; set; }
        public string TypPlatnosci { get; set; }
        public Nullable<int> KlubSprzedajacyId { get; set; }
        public Nullable<int> KlubKupujacyId { get; set; }
    
        public virtual Klub Klub { get; set; }
        public virtual Klub Klub1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SprzedażKupnoZawodnika> SprzedażKupnoZawodnika { get; set; }
    }
}
