//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfermarktDataGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class WartoscZawodnika
    {
        public int Id { get; set; }
        public Nullable<decimal> WartoscRynkowa { get; set; }
        public System.DateTime DataWystawienia { get; set; }
        public Nullable<int> ZawodnikId { get; set; }
        public Nullable<double> WspolczynnikZmianyWartosci { get; set; }
    
        public virtual Zawodnik Zawodnik { get; set; }
    }
}
